### PR TITLE
Accept Python executable from autoproj

### PR DESCRIPTION
**Pull request by AlexanderFabisch**

### CODE REVIEW

**Comment by 2maz** [comment]
cython is also version dependant, so something along the following lines will be needed:

```
    find_program(CYTHON
        NAMES cython${PYTHON_MAJOR_VERION} cython
    )
```

**Comment by AlexanderFabisch** [comment]
> cython is also version dependant, so something along the following lines will be needed:

yes, buuut that only works if we take Cython that has been installed from apt. That's why we use the environment variable `$CYTHON`. Is it possible to get something like CYTHON_EXECUTABLE as a CMake variable from autoproj?

**Comment by 2maz** [comment]
Cython is defined as dependency in the manifest.xml, so depending on your selection of the python version / executable during the autoproj configuration you will have at least either python2 or python3 installed (via apt).
This will also be consistent with the version of the user selection, i.e. here PYTHON_EXECUTABLE.

Your installation might still have both python2 and python3 installed and likewise python-cython or python3-cython. Hence, the correct cython executable needs to be picked explicitly. When you know the python (major) version, that will be sufficient to select the right cython executable.

**Comment by AlexanderFabisch** [comment]
> Your installation might still have both python2 and python3 installed and likewise python-cython or python3-cython. Hence, the correct cython executable needs to be picked explicitly. When you know the python (major) version, that will be sufficient to select the right cython executable.

I personally use cython from pip in my conda installation. My solution is to take `cython${PYTHON_VERSION}` when ${PYTHON_EXECUTABLE} is defined.

**Comment by 2maz** [comment]
Then, how about using the following instead of using cython executable directly?
```
"${PYTHON_EXECUTABLE} -m cython"
```

**Comment by AlexanderFabisch** [comment]
Good idea. That makes the installation a lot simpler. Can you test it?

**Review by 2maz — APPROVED** [review]

**Pull request merged**
