### PR TITLE
fixed dependency

### PR DESCRIPTION
**Pull request by dettmann**

### CODE REVIEW

**Comment by AlexanderFabisch** [comment]
I just merged a fix for that error in Travis and I restarted the build.

**Comment by AlexanderFabisch** [comment]
Ah, sorry, could you rebase on master?

    git fetch <remote> # <remote> should be the main repository
    git rebase <remote>/master

**Comment by dettmann** [comment]
done

**Comment by AlexanderFabisch** [comment]
Great, thanks!

**Pull request merged**
