### PR TITLE
Stage1

### PR DESCRIPTION
**Pull request by AlexanderFabisch**
Reach DFKI software quality stage 1

### CODE REVIEW

**Comment by AlexanderFabisch** [comment]
@planthaber, I need a review. :)

**Comment by planthaber** [comment]
I personally use forks differently:

1. Fork
2. Add repo as second remote git remote add forkremote git@...
3. push dev branch to fork git push forkremote devbranch
4. create PR

But without a socont clone.

**Comment by AlexanderFabisch** [comment]
OK, but this is just a guide for beginners. The experienced developer will know how to do this. ;)

**Comment by planthaber** [comment]
I still think "my way" is easier for beginners ;-) But i'm fine with the merge ;-)

**Comment by AlexanderFabisch** [comment]
Thanks @planthaber , I will add these texts to our guidelines

**Pull request merged**
